### ISSUE TITLE
MNIST image completion

### ISSUE THREAD

**Issue by neighthan** [kasparmartens/NeuralProcesses#2]
Did you try to do the MNIST image completion task with your neural process implementation? I also recently implemented NP (in PyTorch), but I can't get it to work for that task. After seeing your code here, I made a version of my own code that should be ~identical to yours (except in PyTorch). I only did your first experiment, but it worked fine. However, the image completion works no better than my previous implementation. I'd be interested to hear about any results that you had on that task / thoughts on what could be failing there (feel free to close this issue if you aren't interested).

**Comment by kasparmartens** [comment]
Hi Nathan! No, I haven't tried that MNIST experiment, so I don't think I have any general advice what could be failing there.

**Comment by geniki** [comment]
@neighthan you may be interested in my implementation of the MNIST task in Pytorch [here](https://github.com/geniki/neural-processes).

I hope you don't mind me posting this @kasparmartens. Thanks for your repo!

**Comment by neighthan** [comment]
@geniki Your results look much better than anything that I was getting! I'll make sure to look into your code if I'm trying something with neural processes again in the future. Thanks! (now you've got to update to add attention, though - seen the new paper? Always something more!)
