### ISSUE TITLE
Dimensions for decoder g

### ISSUE THREAD

**Issue by kristpapadopoulos** [kasparmartens/NeuralProcesses#6]
Sorry this question might be obvious but I don't understand why n_draws and N_star are taken from [1] from shape.  Shouldn't their dimension be taken from [0].

decoder g -- map (z, x*) -> hidden -> y*
-inputs dimensions
-z_sample has dim [n_draws, dim_z]
- x_star has dim [N_star, dim_x]
  
 n_draws <- z_sample$get_shape()$as_list()[1]
 N_star <- tf$shape(x_star)[1]

**Comment by kasparmartens** [comment]
Hi!

This is because indexing in R starts from 1 :).

**Comment by kristpapadopoulos** [comment]
I figured it was something obvious.  thanks for answering.
